import { QRSlot } from "@/types/qr";

export interface GeneratedFrame {
  id: string;
  name: string;
  imagePath: string;
  aspectRatio: number;
  color: string;
  text: string;
  qrSlot: QRSlot;
}

const greetingSlot: QRSlot = { x: 28, y: 21, width: 34, height: 34 };

export const GENERATED_FRAMES: GeneratedFrame[] = [
  {
    id: `love-cupid`,
    name: `Love Cupid`,
    imagePath: `/frames/love-cupid.svg`,
    aspectRatio: 1,
    color: "#ef7ca0",
    text: "SCAN ME",
    qrSlot: { x: 21.25, y: 20.83, width: 57.5, height: 58.34 },
  },
  ...[
    ["birthday-01", "Birthday Teal"],
    ["birthday-02", "Birthday Pink"],
    ["birthday-03", "Birthday Confetti"],
    ["birthday-04", "Birthday Bunting"],
    ["birthday-05", "Birthday Stars"],
    ["birthday-06", "Birthday Purple"],
    ["birthday-07", "Birthday Balloons"],
  ].map(([id, name], index) => ({
    id,
    name,
    imagePath: `/frames/birthday/frame-${String(index + 1).padStart(2, "0")}.svg`,
    aspectRatio: 1,
    color: ["#159e9b", "#e93682", "#f7c632", "#15a8a1", "#f04b91", "#684376", "#15a8a1"][index],
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  })),
  {
    id: "food-menu-chef",
    name: "Chef",
    imagePath: "/frames/food-menu/frame-chef.svg",
    aspectRatio: 1,
    color: "#55202b",
    text: "SCAN ME",
    qrSlot: { x: 39, y: 62, width: 22, height: 22 },
  },
  {
    id: "food-menu-pizza",
    name: "Pizza",
    imagePath: "/frames/food-menu/frame-pizza.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 37, y: 37, width: 26, height: 26 },
  },
  {
    id: "food-menu-burger",
    name: "Burger",
    imagePath: "/frames/food-menu/frame-burger.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 42, y: 34, width: 16, height: 16 },
  },
  {
    id: "food-menu-receipt",
    name: "Receipt",
    imagePath: "/frames/food-menu/frame-receipt.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 38, y: 39, width: 24, height: 24 },
  },
  {
    id: "food-menu-tray",
    name: "Serving Tray",
    imagePath: "/frames/food-menu/frame-tray.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 40, y: 38, width: 20, height: 20 },
  },
  {
    id: "food-menu-box",
    name: "Delivery Box",
    imagePath: "/frames/food-menu/frame-box.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 40, y: 38, width: 20, height: 20 },
  },
  {
    id: "food-menu-sign",
    name: "Restaurant Sign",
    imagePath: "/frames/food-menu/frame-sign.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 37, y: 38, width: 26, height: 24 },
  },
  {
    id: "food-menu-table",
    name: "Table Menu",
    imagePath: "/frames/food-menu/frame-table.svg",
    aspectRatio: 1,
    color: "#8b1f35",
    text: "SCAN ME",
    qrSlot: { x: 39, y: 40, width: 22, height: 24 },
  },
  {
    id: "valentine-envelope",
    name: "Envelope",
    imagePath: "/frames/valentine/frame-envelope.svg",
    aspectRatio: 1,
    color: "#8f2038",
    text: "SCAN ME",
    qrSlot: { x: 37, y: 42, width: 26, height: 25 },
  },
  {
    id: "valentine-heart",
    name: "Heart",
    imagePath: "/frames/valentine/frame-heart.svg",
    aspectRatio: 1,
    color: "#a9213d",
    text: "SCAN ME",
    qrSlot: { x: 35, y: 34, width: 30, height: 30 },
  },
  {
    id: "valentine-roses",
    name: "Roses",
    imagePath: "/frames/valentine/frame-roses.svg",
    aspectRatio: 1,
    color: "#a92d48",
    text: "SCAN ME",
    qrSlot: { x: 20.42, y: 20.42, width: 59.16, height: 59.16 },
  },
  {
    id: "valentine-calendar",
    name: "Calendar",
    imagePath: "/frames/valentine/frame-calendar.svg",
    aspectRatio: 1,
    color: "#8f2038",
    text: "SCAN ME",
    qrSlot: { x: 38, y: 44, width: 24, height: 24 },
  },
  {
    id: "valentine-lovebirds",
    name: "Lovebirds",
    imagePath: "/frames/valentine/frame-lovebirds.svg",
    aspectRatio: 1,
    color: "#7b3144",
    text: "SCAN ME",
    qrSlot: { x: 36, y: 36, width: 28, height: 28 },
  },
  {
    id: "valentine-vine",
    name: "Floral Vine",
    imagePath: "/frames/valentine/frame-vine.svg",
    aspectRatio: 1,
    color: "#d8aaa2",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: "valentine-teddy",
    name: "Teddy Bear",
    imagePath: "/frames/valentine/frame-teddy.svg",
    aspectRatio: 1,
    color: "#b7794c",
    text: "SCAN ME",
    qrSlot: { x: 33, y: 49, width: 34, height: 25 },
  },
  {
    id: "valentine-gifts",
    name: "Gift Boxes",
    imagePath: "/frames/valentine/frame-gifts.svg",
    aspectRatio: 1,
    color: "#a64a55",
    text: "SCAN ME",
    qrSlot: { x: 29.17, y: 29.17, width: 41.66, height: 41.66 },
  },
  {
    id: "shopping-bag",
    name: "Shopping Bag",
    imagePath: "/frames/shopping/frame-bag.svg",
    aspectRatio: 1,
    color: "#ad3b54",
    text: "SCAN ME",
    qrSlot: { x: 39.17, y: 41.67, width: 21.66, height: 21.66 },
  },
  {
    id: "shopping-tag",
    name: "Price Tag",
    imagePath: "/frames/shopping/frame-tag.svg",
    aspectRatio: 1,
    color: "#5b9d95",
    text: "SCAN ME",
    qrSlot: { x: 35, y: 35.83, width: 31.66, height: 31.66 },
  },
  {
    id: "shopping-gift",
    name: "Gift Box",
    imagePath: "/frames/shopping/frame-gift.svg",
    aspectRatio: 1,
    color: "#e7c68e",
    text: "SCAN ME",
    qrSlot: { x: 21.67, y: 21.67, width: 56.66, height: 56.66 },
  },
  {
    id: "shopping-cart",
    name: "Shopping Cart",
    imagePath: "/frames/shopping/frame-cart.svg",
    aspectRatio: 1,
    color: "#5b9d95",
    text: "SCAN ME",
    qrSlot: { x: 45.83, y: 36.67, width: 13.34, height: 13.34 },
  },
  {
    id: "shopping-discount",
    name: "Discount Badge",
    imagePath: "/frames/shopping/frame-discount.svg",
    aspectRatio: 1,
    color: "#e9d5a0",
    text: "SCAN ME",
    qrSlot: { x: 27.5, y: 27.5, width: 45, height: 45 },
  },
  {
    id: "shopping-shirt",
    name: "Clothing",
    imagePath: "/frames/shopping/frame-shirt.svg",
    aspectRatio: 1,
    color: "#f0dfc1",
    text: "SCAN ME",
    qrSlot: { x: 39.58, y: 39.17, width: 20.84, height: 23.34 },
  },
  {
    id: "shopping-receipt",
    name: "Shopping Receipt",
    imagePath: "/frames/shopping/frame-receipt.svg",
    aspectRatio: 1,
    color: "#fffaf0",
    text: "SCAN ME",
    qrSlot: { x: 37.5, y: 43.33, width: 25, height: 14.17 },
  },
  {
    id: "shopping-store",
    name: "Storefront",
    imagePath: "/frames/shopping/frame-store.svg",
    aspectRatio: 1,
    color: "#5b9d95",
    text: "SCAN ME",
    qrSlot: { x: 39.17, y: 44.17, width: 21.66, height: 18.33 },
  },
  {
    id: "food-expanded-seafood",
    name: "Seafood Platter",
    imagePath: "/frames/food-expanded/frame-seafood.svg",
    aspectRatio: 1,
    color: "#23455a",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: "food-expanded-steak",
    name: "Steakhouse",
    imagePath: "/frames/food-expanded/frame-steak.svg",
    aspectRatio: 1,
    color: "#8e3e35",
    text: "SCAN ME",
    qrSlot: { x: 31.67, y: 31.67, width: 36.66, height: 36.66 },
  },
  {
    id: "food-expanded-pizza-box",
    name: "Pizza Box",
    imagePath: "/frames/food-expanded/frame-pizza-box.svg",
    aspectRatio: 1,
    color: "#e3b36d",
    text: "SCAN ME",
    qrSlot: { x: 31.67, y: 31.67, width: 36.66, height: 36.66 },
  },
  {
    id: "food-expanded-sushi",
    name: "Sushi Mat",
    imagePath: "/frames/food-expanded/frame-sushi.svg",
    aspectRatio: 1,
    color: "#d4b06e",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: "food-expanded-bakery",
    name: "Bakery",
    imagePath: "/frames/food-expanded/frame-bakery.svg",
    aspectRatio: 1,
    color: "#b77a3f",
    text: "SCAN ME",
    qrSlot: { x: 25.83, y: 25.83, width: 48.34, height: 48.34 },
  },
  {
    id: "food-expanded-sandwich",
    name: "Sandwich",
    imagePath: "/frames/food-expanded/frame-sandwich.svg",
    aspectRatio: 1,
    color: "#e5ba78",
    text: "SCAN ME",
    qrSlot: { x: 39.17, y: 33.33, width: 21.66, height: 21.66 },
  },
  {
    id: "food-expanded-juice",
    name: "Juice Bar",
    imagePath: "/frames/food-expanded/frame-juice.svg",
    aspectRatio: 1,
    color: "#f1ad44",
    text: "SCAN ME",
    qrSlot: { x: 29.17, y: 29.17, width: 41.66, height: 41.66 },
  },
  {
    id: "food-expanded-wine",
    name: "Wine List",
    imagePath: "/frames/food-expanded/frame-wine.svg",
    aspectRatio: 1,
    color: "#444444",
    text: "SCAN ME",
    qrSlot: { x: 28.33, y: 28.33, width: 43.34, height: 43.34 },
  },
  {
    id: "food-expanded-burrito",
    name: "Burrito",
    imagePath: "/frames/food-expanded/frame-burrito.svg",
    aspectRatio: 1,
    color: "#dfb466",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: "food-expanded-noodles",
    name: "Noodle Box",
    imagePath: "/frames/food-expanded/frame-noodles.svg",
    aspectRatio: 1,
    color: "#d9914b",
    text: "SCAN ME",
    qrSlot: { x: 31.67, y: 31.67, width: 36.66, height: 36.66 },
  },
  {
    id: "food-expanded-cafe",
    name: "Cafe Menu",
    imagePath: "/frames/food-expanded/frame-cafe.svg",
    aspectRatio: 1,
    color: "#8f5b39",
    text: "SCAN ME",
    qrSlot: { x: 30, y: 30, width: 40, height: 40 },
  },
  {
    id: "food-expanded-salad",
    name: "Salad Bowl",
    imagePath: "/frames/food-expanded/frame-salad.svg",
    aspectRatio: 1,
    color: "#75a34f",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: "food-expanded-coffee",
    name: "Coffee Cup",
    imagePath: "/frames/food-expanded/frame-coffee.svg",
    aspectRatio: 1,
    color: "#54202b",
    text: "SCAN ME",
    qrSlot: { x: 28.33, y: 28.33, width: 43.34, height: 43.34 },
  },
  {
    id: "standard-category-viewfinder",
    name: "Viewfinder",
    imagePath: "/frames/standard-category/frame-viewfinder.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 21.67, y: 21.67, width: 56.66, height: 56.66 },
  },
  {
    id: "standard-category-rounded-pill",
    name: "Rounded Pill",
    imagePath: "/frames/standard-category/frame-rounded-pill.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 22.5, y: 22.5, width: 55, height: 55 },
  },
  {
    id: "standard-category-corner-badge",
    name: "Corner Badge",
    imagePath: "/frames/standard-category/frame-corner-badge.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 22.92, y: 22.92, width: 54.16, height: 54.16 },
  },
  {
    id: "standard-category-phone",
    name: "Phone Outline",
    imagePath: "/frames/standard-category/frame-phone.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 37.92, y: 22.5, width: 24.16, height: 50 },
  },
  {
    id: "standard-category-dashed",
    name: "Dashed Viewfinder",
    imagePath: "/frames/standard-category/frame-dashed.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 22.5, y: 22.5, width: 55, height: 55 },
  },
  {
    id: "standard-category-inset-arrow",
    name: "Inset Arrow",
    imagePath: "/frames/standard-category/frame-inset-arrow.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 29.17, width: 50, height: 50 },
  },
  {
    id: "standard-category-offset",
    name: "Offset Squares",
    imagePath: "/frames/standard-category/frame-offset.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 28.33, y: 31.67, width: 53.34, height: 53.34 },
  },
  {
    id: "standard-category-ticket",
    name: "Ticket Stub",
    imagePath: "/frames/standard-category/frame-ticket.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 27.5, width: 50, height: 39.17 },
  },
  {
    id: "standard-category-circle",
    name: "Circle Outline",
    imagePath: "/frames/standard-category/frame-circle.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 22.5, y: 22.5, width: 55, height: 55 },
  },
  {
    id: "standard-category-star",
    name: "Star Inset",
    imagePath: "/frames/standard-category/frame-star.svg",
    aspectRatio: 1,
    color: "#111111",
    text: "SCAN ME",
    qrSlot: { x: 41.67, y: 41.67, width: 16.66, height: 16.66 },
  },
  {
    id: "standard-category-confetti",
    name: "Confetti Corners",
    imagePath: "/frames/standard-category/frame-confetti.svg",
    aspectRatio: 1,
    color: "#6aa9a3",
    text: "SCAN ME",
    qrSlot: { x: 21.67, y: 21.67, width: 56.66, height: 56.66 },
  },
  {
    id: "standard-category-marble-circle",
    name: "Marble Circle",
    imagePath: "/frames/standard-category/frame-marble-circle.svg",
    aspectRatio: 1,
    color: "#777777",
    text: "SCAN ME",
    qrSlot: { x: 22.5, y: 22.5, width: 55, height: 55 },
  },
  {
    id: `g-1-1`,
    name: `Greeting 1`,
    imagePath: `/frames/g-1/frame-1.png`,
    aspectRatio: 341 / 297,
    color: "#0f766e",
    text: "SCAN ME",
    qrSlot: greetingSlot,
  },
  {
    id: `g-1-2`,
    name: `Greeting 2`,
    imagePath: `/frames/g-1/frame-2.png`,
    aspectRatio: 341 / 297,
    color: "#0f766e",
    text: "SCAN ME",
    qrSlot: greetingSlot,
  },
  {
    id: `g-1-3`,
    name: `Greeting 3`,
    imagePath: `/frames/g-1/frame-3.png`,
    aspectRatio: 341 / 297,
    color: "#0f766e",
    text: "SCAN ME",
    qrSlot: greetingSlot,
  },
  {
    id: `g-1-4`,
    name: `Greeting 4`,
    imagePath: `/frames/g-1/frame-4.png`,
    aspectRatio: 341 / 297,
    color: "#0f766e",
    text: "SCAN ME",
    qrSlot: greetingSlot,
  },
  {
    id: `g-1-5`,
    name: `Greeting 5`,
    imagePath: `/frames/g-1/frame-5.png`,
    aspectRatio: 341 / 297,
    color: "#0f766e",
    text: "SCAN ME",
    qrSlot: greetingSlot,
  },
  {
    id: `g-1-6`,
    name: `Greeting 6`,
    imagePath: `/frames/g-1/frame-6.png`,
    aspectRatio: 341 / 297,
    color: "#0f766e",
    text: "SCAN ME",
    qrSlot: greetingSlot,
  },
  {
    id: `love-1`,
    name: `Love 1`,
    imagePath: `/frames/love/frame-1.png`,
    aspectRatio: 1,
    color: "#b45309",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `love-2`,
    name: `Love 2`,
    imagePath: `/frames/love/frame-2.png`,
    aspectRatio: 1,
    color: "#b45309",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `love-3`,
    name: `Love 3`,
    imagePath: `/frames/love/frame-3.png`,
    aspectRatio: 1,
    color: "#b45309",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `love-4`,
    name: `Love 4`,
    imagePath: `/frames/love/frame-4.png`,
    aspectRatio: 1,
    color: "#b45309",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `love-5`,
    name: `Love 5`,
    imagePath: `/frames/love/frame-5.png`,
    aspectRatio: 1,
    color: "#b45309",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `love-6`,
    name: `Love 6`,
    imagePath: `/frames/love/frame-6.png`,
    aspectRatio: 1,
    color: "#b45309",
    text: "SCAN ME",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `job-consultant`,
    name: `Consultant`,
    imagePath: `/frames/job/frame-consultant.svg`,
    aspectRatio: 1,
    color: "#1e3a8a",
    text: "CONSULTANT",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `job-engineer`,
    name: `Engineer`,
    imagePath: `/frames/job/frame-engineer.svg`,
    aspectRatio: 1,
    color: "#64748b",
    text: "ENGINEER",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `job-medicine`,
    name: `Medicine`,
    imagePath: `/frames/job/frame-medicine.svg`,
    aspectRatio: 1,
    color: "#7dd3fc",
    text: "MEDICINE",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `job-logistics-1`,
    name: `Logistics 1`,
    imagePath: `/frames/job/frame-logistics-1.svg`,
    aspectRatio: 1,
    color: "#475569",
    text: "LOGISTICS",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `job-logistics-2`,
    name: `Logistics 2`,
    imagePath: `/frames/job/frame-logistics-2.svg`,
    aspectRatio: 1,
    color: "#334155",
    text: "LOGISTICS",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `job-global-business`,
    name: `Global Business`,
    imagePath: `/frames/job/frame-global-business.svg`,
    aspectRatio: 1,
    color: "#94a3b8",
    text: "GLOBAL BUSINESS",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `food-fine-dining`,
    name: `Fine Dining`,
    imagePath: `/frames/food/frame-fine-dining.svg`,
    aspectRatio: 1,
    color: "#b45309",
    text: "FINE DINING",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `food-cafe-menu`,
    name: `Cafe Menu`,
    imagePath: `/frames/food/frame-cafe-menu.svg`,
    aspectRatio: 1,
    color: "#a16207",
    text: "CAFE MENU",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `food-farm`,
    name: `Farm-to-Table`,
    imagePath: `/frames/food/frame-farm.svg`,
    aspectRatio: 1,
    color: "#8b5e34",
    text: "FARM-TO-TABLE",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `food-sushi`,
    name: `Sushi Menu`,
    imagePath: `/frames/food/frame-sushi.svg`,
    aspectRatio: 1,
    color: "#475569",
    text: "SUSHI MENU",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `food-pizza-delivery`,
    name: `Pizza Delivery`,
    imagePath: `/frames/food/frame-pizza-delivery.svg`,
    aspectRatio: 1,
    color: "#c2410c",
    text: "PIZZA DELIVERY",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `food-global-flavors`,
    name: `Global Flavors`,
    imagePath: `/frames/food/frame-global-flavors.svg`,
    aspectRatio: 1,
    color: "#64748b",
    text: "GLOBAL FLAVORS",
    qrSlot: { x: 25, y: 25, width: 50, height: 50 },
  },
  {
    id: `standard-classic`,
    name: `Classic Border`,
    imagePath: `/frames/standard/frame-01-classic.svg`,
    aspectRatio: 1,
    color: "#222222",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-double`,
    name: `Double Line`,
    imagePath: `/frames/standard/frame-02-double.svg`,
    aspectRatio: 1,
    color: "#333333",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-corner`,
    name: `Corner Scroll`,
    imagePath: `/frames/standard/frame-03-corner.svg`,
    aspectRatio: 1,
    color: "#333333",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-dotted`,
    name: `Dotted Edge`,
    imagePath: `/frames/standard/frame-04-dotted.svg`,
    aspectRatio: 1,
    color: "#222222",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-vintage`,
    name: `Vintage`,
    imagePath: `/frames/standard/frame-05-vintage.svg`,
    aspectRatio: 1,
    color: "#555555",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-geometric`,
    name: `Geometric`,
    imagePath: `/frames/standard/frame-06-geometric.svg`,
    aspectRatio: 1,
    color: "#333333",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-rounded`,
    name: `Rounded`,
    imagePath: `/frames/standard/frame-07-rounded.svg`,
    aspectRatio: 1,
    color: "#222222",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-ornate`,
    name: `Ornate`,
    imagePath: `/frames/standard/frame-08-ornate.svg`,
    aspectRatio: 1,
    color: "#444444",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-lines`,
    name: `Fine Lines`,
    imagePath: `/frames/standard/frame-09-lines.svg`,
    aspectRatio: 1,
    color: "#444444",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-diamond`,
    name: `Diamond Corners`,
    imagePath: `/frames/standard/frame-10-diamond.svg`,
    aspectRatio: 1,
    color: "#333333",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-minimal`,
    name: `Minimal`,
    imagePath: `/frames/standard/frame-11-minimal.svg`,
    aspectRatio: 1,
    color: "#222222",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  {
    id: `standard-filigree`,
    name: `Filigree`,
    imagePath: `/frames/standard/frame-12-filigree.svg`,
    aspectRatio: 1,
    color: "#333333",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  },
  ...[
    ["triple", "Triple Line"],
    ["bracket", "Bracket Corners"],
    ["wave", "Wave Edge"],
    ["arch", "Arch Border"],
    ["dashed", "Dashed Edge"],
    ["circles", "Circle Corners"],
    ["square", "Square Corners"],
    ["braid", "Braid Corners"],
    ["inner", "Inner Border"],
    ["leaf", "Leaf Corners"],
    ["panel", "Panel Corners"],
    ["mat", "Gallery Mat"],
    ["corner-dots", "Corner Dots"],
    ["rail", "Rail Lines"],
    ["cameo", "Cameo"],
    ["cross", "Cross Corners"],
    ["ink", "Ink Border"],
    ["rope", "Rope Edge"],
    ["portal", "Portal"],
    ["star", "Star Corners"],
    ["etched", "Etched"],
    ["soft", "Soft Round"],
    ["engraved", "Engraved"],
    ["gallery", "Gallery Triple"],
  ].map(([slug, name], index) => ({
    id: `standard-${slug}`,
    name,
    imagePath: `/frames/standard/frame-${String(index + 13).padStart(2, "0")}-${slug}.svg`,
    aspectRatio: 1,
    color: "#444444",
    text: "SCAN ME",
    qrSlot: { x: 20, y: 20, width: 60, height: 60 },
  })),
];

export function getGeneratedFrame(frameId: string) {
  return GENERATED_FRAMES.find((frame) => frame.id === frameId);
}